spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_voter?serverTimezone=Asia/Shanghai
    username: root
    password: admin
  # mybatis
  # mapper-location: classpath*:mapper/*.xml
  # 自定义
voter:
  redis:
    host: 39.99.212.
    port: 6379
    pass:
  aes:
    passkey: dP0ykNOnMdKFaXCIOnXckg==